hex_rails_jim_weirich/config/routes.rb
Wyriki::Application.routes.draw do

  resources :permissions

  resources :users

  resources :wikis do
    resources :pages
  end

  resource :session

  get ':wiki/:page/new' => 'pages#new_named', as: :new_named_page
  get ':wiki/:page' => 'pages#show_named', as: :named_page

  root "wikis#index"

end

hex_rails_jim_weirich/app/views/pages/edit.html.erb
<div class="row">
  <div class="columns small-8">
    <h1>Edit Page: <%= @page.name %></h1>
  </div>
</div>

<div class="row">
  <div class="columns small-12">
    <%= form_for([@wiki, @page]) do |f| %>
    <%= render "common/errors", model: @page %>
    <p>
      <%= f.text_area :content, class: 'page-content' %>
    </p>
    <p>
      <%= f.submit button_css %>
      <%= link_to "Cancel", [@wiki, @page], button_css %>
    </p>
    <% end %>
  </div>
</div>

hex_rails_jim_weirich/app/views/pages/new.html.erb
<h1 id="pagetitle">Create Page</h1>

<div class="row">
  <div class="columns small-12">
    <%= form_for([@wiki, @page]) do |f| %>
    <%= render "common/errors", model: @page %>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :content %><br />
      <%= f.text_area :content, class: 'page-content' %>
    </p>
    <p>
      <%= f.submit button_css %>
      <%= link_to "Cancel", @wiki, button_css %>
    </p>
    <% end %>
  </div>
</div>

hex_rails_jim_weirich/app/views/pages/show.html.erb
<div class="row separate">
  <div class="small-6 columns">
    <h1 id="page-title"><%= @page.name %></h1>
  </div>
  <div class="small-4 columns">
    <p class="actions">
      <%= link_to "Edit", edit_wiki_page_path(@page.wiki, @page), button_css %>
      <%= link_to "Delete", wiki_page_path(@page.wiki, @page),
          button_css.merge(
            method: :delete,
            data: { confirm: "Do you really want to delete page #{@page.name}?" })
          %>
    </p>
  </div>
</div>

<div class="row">
  <div class="small-12 columns" id="page-content">
    <%= @page.html_content(self).html_safe %>
  </div>
</div>