hex_rails_jim_weirich/config/routes.rb
Wyriki::Application.routes.draw do

  resources :permissions

  resources :users

  resources :wikis do
    resources :pages
  end

  resource :session

  get ':wiki/:page/new' => 'pages#new_named', as: :new_named_page
  get ':wiki/:page' => 'pages#show_named', as: :named_page

  root "wikis#index"

end

hex_rails_jim_weirich/app/models/biz/wiki.rb
require_dependency './app/models/biz/model'

module Biz
  class Wiki < Model

    # Is the page in the defined in the repository?
    def page?(repo, page_name)
      page = repo.find_named_page(data.name, page_name)
      ! page.nil?
    end
  end
end

hex_rails_jim_weirich/app/models/wiki.rb
class Wiki < ActiveRecord::Base
  include Biz::Mimic

  has_many :pages, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :home_page,
    presence: true,
    format: { with: /\A([A-Z][a-z0-9]+){2,}\Z/, message: "is not a wiki name" }

  def self.active_wikis
    all.order("name")
  end
end

hex_rails_jim_weirich/app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include WikiRunners

  def index
    run(Index) do |on|
      on.success { |wikis|
        @wikis = wikis
      }
    end
  end

  def show
    @wiki = run(Show, params[:id]).first
  end

  def new
    @wiki = run(New).first
  end

  def create
    run(Create, wiki_params) do |on|
      on.success { |wiki|
        redirect_to wikis_path, notice: "Wiki #{wiki.name} created"
      }
      on.failure { |wiki|
        @wiki = wiki
        render :new
      }
    end
  end

  def edit
    @wiki = run(Edit, params[:id])
  end

  def update
    run(Update, params[:id]) do |on|
      on.success { |wiki|
        redirect_to wikis_path, notice: "Wiki #{wiki.name} updated"
      }
      on.failure { |wiki|
        @wiki = wiki
        render :edit
      }
    end
  end

  def destroy
    wiki_name = run(Destroy, params[:id]).first
    redirect_to wikis_path, notice: "Wiki #{wiki_name} deleted"
  end

  private

  def wiki_params
    params.require(:wiki).permit(:name, :home_page)
  end
end

hex_rails_jim_weirich/app/helpers/wikis_helper.rb
module WikisHelper
end

hex_rails_jim_weirich/app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
<%= render "common/errors", model: @wiki %>
<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :home_page %><br />
  <%= f.text_field :home_page %>
</p>
<p>
  <%= f.submit class: "small radius button" %>
  <%= link_to "Cancel", @wiki, class: "small radius button" %>
</p>
<% end %>

hex_rails_jim_weirich/app/views/wikis/edit.html.erb
<h1>Edit Wiki: <%= @wiki.name %></h1>

<%= render "form" %>

hex_rails_jim_weirich/app/views/wikis/index.html.erb
<div class="row separate">
  <div class="columns small-8">
    <h1>Wikis</h1>
  </div>
  <div class="columns small-4">
    <p class="actions">
      <%= link_to "Create new wiki", new_wiki_path, button_css %>
    </p>
  </div>
</div>

<div class="row" id="wikilist">
  <div class="columns small-8">
    <ul>
      <% @wikis.each do |wiki| %>
      <li><%= link_to wiki.name, wiki %></li>
      <% end %>
    </ul>
  </div>
</div>

hex_rails_jim_weirich/app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render "form" %>

hex_rails_jim_weirich/app/views/wikis/show.html.erb
<div class="row separate">
  <div class="columns small-6">
    <h1>Wiki: <%= @wiki.name %></h1>
  </div>
  <div class="columns small-6">
    <p class="actions">
      <%= link_to "Edit", edit_wiki_path(@wiki), button_css %>
      <%= link_to "Delete", wiki_path(@wiki),
          button_css.merge(
            method: :delete,
            data: { confirm: "Really delete wiki #{@wiki.name}?" })
          %>
    </p>
  </div>
</div>

<p>
  Home Page:
  <%= link_to @wiki.home_page, named_page_path(@wiki.name, @wiki.home_page) %>
</p>

<div class="row">
  <div class="columns small-8">
    <h2>Pages</h2>
  </div>
  <div class="columns small-4">
    <p class="actions">
      <%= link_to "Create page", new_wiki_page_path(@wiki), button_css %>
    </p>
  </div>
</div>


<ul>
  <% @wiki.pages.each do |page| %>
  <li>
    <%= link_to page.name, named_page_link(page) %>
  </li>
  <% end %>
</ul>