hex_rails_jim_weirich/config/routes.rb
Wyriki::Application.routes.draw do

  resources :permissions

  resources :users

  resources :wikis do
    resources :pages
  end

  resource :session

  get ':wiki/:page/new' => 'pages#new_named', as: :new_named_page
  get ':wiki/:page' => 'pages#show_named', as: :named_page

  root "wikis#index"

end

hex_rails_jim_weirich/app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
<% flash.each do |key, msg| %>
<div class="row">
  <div class="colums small-12">
    <p class="flash flash_<%= key %>">
      <%= msg %>
    </p>
  </div>
</div>
<% end %>
<% end %>

hex_rails_jim_weirich/app/views/layouts/_header.html.erb
<div class="row header">
  <div class="small-8 columns">
    <h1>
      <%= link_to "WyRiki", wikis_path %>
      <% if @wiki %>
      / <%= link_to @wiki.name, @wiki %>
      <% end %>
    </h1>
  </div>
  <div class="small-4 columns">
    <p class="actions">
      <% if current_user.logged_in? %>
      <%= current_user.name %>
      (<%= link_to "sign out", session_path, method: :delete %>)
      <% else %>
      <%= link_to "Sign in", new_session_path %>
      <% end %>
    </p>
  </div>
</div>

hex_rails_jim_weirich/app/views/layouts/_sidebar.html.erb
<div class="row sidebar" >
  <h3>Navigate</h3>

  <ul>
    <li><%= link_to "Wiki List", wikis_path  %></li>
    <li><%= link_to "User List", users_path  %></li>
  </ul>
</div>

hex_rails_jim_weirich/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wyriki</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>

  <div class="row">
    <div class="small-12 large-12 columns">
      <%= render "layouts/flash_messages" %>
    </div>
  </div>

  <div class="row">
    <div class="small-8 medium-9 large-10 columns">
      <%= yield %>
    </div>
    <div class="small-4 medium-3 large-2 columns">
      <%= render "layouts/sidebar" %>
    </div>
  </div>

</body>
</html>